import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "@/app/Provider";
import Header from "@/components/Header";
import NextTopLoader from "nextjs-toploader";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        suppressContentEditableWarning
        suppressHydrationWarning
      >
        <Provider>
          <NextTopLoader showSpinner={false} color="lightblue" />
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
